org.gradle.jvmargs=-Xms2560m -Xmx5632m -XX:ReservedCodeCacheSize=512m -XX:MaxMetaspaceSize=768m -XX:+UseG1GC -XX:+ParallelRefProcEnabled -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xms1024m -Xmx2048m -XX:+UseG1GC
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configureondemand=true
kotlin.incremental=true
kotlin.incremental.useClasspathSnapshot=true
org.gradle.warning.mode=none
org.gradle.problems.report=false

# these were used to compile faster in my phone (yes my phone is a vfs inside a terminal emulator which is termux)